### ISSUE TITLE
Blocking issue with power consumption demo PWR_ModesSelection

### ISSUE THREAD

**Issue by bigbearishappy** [STMicroelectronics/STM32CubeU5#20]
**Describe the set-up**

 * The board
NUCLEO-U575ZI-Q
 * IDE or at least the compiler and its version
STM32CubeIDE
Version: 1.10.1
Build: 12716_20220707_0928 (UTC)
compiler:
gcc 10.3-2021.10

**Describe the bug (skip if none)**
The board can not enter the relative low power mode.

**How to reproduce the bug**
1 remove the JP5 and connect an amperemeter to it
1 compile and download the demo code under Projects\NUCLEO-U575ZI-Q\Examples\PWR\PWR_ModesSelection
2 config the low power via the usart
3 finish the config and enter the low power mode
4 in STOP0 mode the current consumption should be about 39uA，but it's about 7mA

**Additional context**
I did some work on tracing the issue. And I find the program blocked after run into the function [system_config](https://github.com/STMicroelectronics/STM32CubeU5/blob/2e2b3e4733ddcde7af1e91f1c27ef7bea84389ce/Projects/NUCLEO-U575ZI-Q/Examples/PWR/PWR_ModesSelection/Src/lowpower_scenarios.c#L182)

I hope someone can help me out~

**Comment by bridadan** [comment]
I can confirm I'm having the same issue. I'm seeing a ~7.5mA current draw no matter the PWR mode I select.

**Comment by HBOSTM** [comment]
Hello @bigbearishappy
We confirm the abnormal behavior you reported. It has been reported to our development teams for deeper analysis. We will get back to you as soon we have updates.

With regards,

**Comment by HBOSTM** [comment]
ST Internal Reference: 141762

**Comment by LaVoute974** [comment]
Hello, I'm having the same issue (consumption arround 5mA in every mode), do you have any updates on this ?

**Comment by HBOSTM** [comment]
Hi @LaVoute974 ,

Thank you for your contribution. This issue has been fixed. Could you please try with the last version **v1.2.0**.

Best Regards,
