### ISSUE TITLE
B-U585I-IOT02A\Applications\TFM_Appli has been removed by 4782b741ef commit

### ISSUE THREAD

**Issue by massibartoli** [STMicroelectronics/STM32CubeU5#25]
**Describe the set-up**
Board: B-U585I-IOT02A

**Describe the bug (skip if none)**
Hello everyone,
I have an issue with the latest STM32CubeU5 release (v1.2.0): it looks that the commit 4782b741ef removes the Projects/B-U585I-IOT02A\Applications\TFM_Appli application which should be not the purpose according to the release note.

**Screenshots**
Release note excerpt:
![image](https://user-images.githubusercontent.com/90269552/229723794-29552020-8bca-45ce-bf6c-8d2dd3551ab4.png)

**Comment by TOUNSTM** [comment]
Hello @massibartoli,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,

**Comment by TOUNSTM** [comment]
Hello @massibartoli,

Some projects have been made unavailable in our repositories on GitHub as they are subject to "click-thru" licenses.
If needed, the removed items can be found in the full firmware package on st.com. 

Please allow me thus to close this thread. Thank you for you comprehension and for contribution.

With Regards,
