### ISSUE TITLE
USBX Host examples - general issue

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/STM32CubeU5#30]
There are several USBX Host examples built for **STM32U5x9J-DK** board ([STM32U5A9J-DK](https://www.st.com/en/evaluation-tools/stm32u5a9j-dk.html) MB1829, others?)
https://github.com/STMicroelectronics/STM32CubeU5/tree/main/Projects/STM32U5x9J-DK/Applications/USBX

The little problem is that this board doses NOT have UCPD source capability so it cannot power the attached devices, unless non-standard power config is used. That is: 2nd JP4 jumper in 5V_UCPD position, current flows through Q1 internal diode (Imax=1.4A only!) with significant 0.4V voltage drop at 1A, or **powered** USB hub is used. Definitely, not the best board selection for this kind of examples. 
According to [README](https://github.com/STMicroelectronics/STM32CubeU5/tree/main/Projects/STM32U5x9J-DK/Applications/USBX/Ux_Host_HUB_HID_MSC), examples have been tested with non-officially-existent (!) STM32U599J-DK board, but luckily the attached IOC file contains STM32U5A9J config.
[README](https://github.com/STMicroelectronics/STM32CubeU5/tree/main/Projects/STM32U5x9J-DK/Applications/USBX/Ux_Host_HUB_HID_MSC) does not clearly state whether or not USB hub is required or a single device, e.g. mouse, can be connected directly. Perhaps not, but it is unclear.

I think it would make much more sense to build USBX Host examples for the **[B-U585I-IOT02A](https://www.st.com/en/evaluation-tools/b-u585i-iot02a.html)** (MB1551) board which has both UCPD sink and source capability and is more cost-effective than [STM32U575I-EV](https://www.st.com/en/evaluation-tools/stm32u575i-ev.html) board.

**Comment by tdjastrzebski** [comment]
Another board which could be used for USBX Host example is [NUCLEO-U5A5ZJ-Q](https://www.st.com/en/evaluation-tools/nucleo-u5a5zj-q.html#overview). At least it can be configured to provide USB power (SB8-10) and, unlike [B-U585I-IOT02A](https://www.st.com/en/evaluation-tools/b-u585i-iot02a.html), contains MCU which has high speed transmitter (HS_OTG).

**Comment by pauleffect90** [comment]
I have a u5a5 nucleo board and I stand in complete awe at how much of a joke this line of MCUs is. Maybe they leaned a little too much on interns or cheap off-shore 50-a-dime programmers, maybe they're simply in over their heads, I've no clue - but I've yet to encounter this much of a mess in 10y working as an embedded engineer.

![image](https://github.com/STMicroelectronics/STM32CubeU5/assets/46864811/095fc8bd-9bf0-456a-9c17-817afadb05a6)
One would expect the value of PLLN to be 16 / 1 * 80 = 1280Mhz. Nope, it's 1328 Mhz.
No wonder I couldn't even send a "hello world" string over UART. My clocks were all messed up by CubeMx - latest version. This only happens for U5A5.

As for the USB Host, 0 examples. There's actually no single USB HS example in the entire U5 repository. Because it's not an important peripheral and neither a complex one.

Id like to say Im surprised but I got to chat with some ST engineers at embedded world last years and they had no clue whatsoever what even the most basic features of U5 mean - like the RAMCFG tab.

I had hoped to port an F4 project over to U5. Guess I'll be going with an NXP.

**Comment by tdjastrzebski** [comment]
@pauleffect90 Do you mean Embedded World in Nuremberg? I had the same impression, but I thought maybe they were not allowed to give full details until the release day.
Nevertheless, ST is a company which is yet to realize that time to market matter a lot to their customers and these days the main factor is SOFTWARE, not hardware.

**Comment by tdjastrzebski** [comment]
@pauleffect90 I think ST is just not a solution for startups and very small companies. I do not believe they do not have dedicated first-class support for selected large players.
That would be OK if they did not pretend to be something else misleading lots of engineers like us. What we experience then is simply a clash between reality and such build expectations.
I am probably going to finish my current project with ST. It is delayed several months, I had to write own I2C/SMBus driver from scratch, found lots HAL and bugs and many RMxxxx documentation mistakes. Overall, it is a terrible experience, I hope never again. Definitely next time I will at least try NXP - thank you.
I got USB-OTG working as a host using modified Nucleo-U5A5ZJ-Q board. The main issue I described in ST forum [here](https://community.st.com/t5/stm32-mcus-products/why-otg-hs-usb-usbx-host-on-stm32u5axx-just-does-not-work-2/m-p/594899/highlight/true#M224140).
For build I use my custom tool [cppbuild ](https://github.com/tdjastrzebski/cppbuild)- fast, simple and very effective. It does full dependency analysis, but this version is not published yet. Sample project with full VS Code config [here](https://github.com/tdjastrzebski/STM32F769I-DISCO-LVGL).

**Comment by pauleffect90** [comment]
> I got USB-C working as a host using modified Nucleo-U5A5ZJ-Q board
Could I perhaps trouble you with sharing your solution? I must confess, coming from a crunch period of ~ 2 years, I am at my wits end, my brain simply refuses to function normally.

> found lots of HAL bugs
I know what you mean. It's less like programming and more like a "brute force" experience. Try adding a delay. Hmm, maybe deinitializing and reinitializing will work. Oh, this only works if... so on, and so forth. And hunting for bugs in a 5000 line file chaotically written (or maybe generated?) by an intern is anything but fun (and you can tell it's sub-par code by the broken english comments). I won't even go into identical if-else branches or the general bloatware feel of the code.

All in all, I managed to port the entire F4 project to the aforementioned NXP in less than one week (including some custom UVC drivers). In one week I still haven't managed to plug a damned usb device into this board. :))

**Comment by tdjastrzebski** [comment]
https://drive.google.com/file/d/1HqLvgRnVtlshHYOxKRAzwTFAdd5a925U/view?usp=sharing
Just keep in mind board needs to provide power. SB8-10 needs to be shorten, additional JP6 jumper in 5V_USB_C position is needed.

**Comment by pauleffect90** [comment]
I left a private message for you on the st community forum for you. Thanks again for all your help.

**Comment by ALABSTM** [comment]
Dear all,

Please excuse this delayed reply.

@tdjastrzebski and @pauleffect90, regarding the host examples provided for boards such as the [STM32U5A9J-DK](https://www.st.com/en/evaluation-tools/stm32u5a9j-dk.html), they are provided **only as reference**. Indeed, such boards are **sink devices** by default and, hence, do not support the VBUS Drive feature.

This is **indicated** in the `README.md` files in a note, as shown below:

https://github.com/STMicroelectronics/STM32CubeU5/blob/c8fcb26ff629cf7c2a3b2c60e6121625eaa5ca2d/Projects/STM32U5x9J-DK/Applications/USBX/Ux_Host_CDC_ACM/README.md?plain=1#L118-L124

https://github.com/STMicroelectronics/STM32CubeU5/blob/c8fcb26ff629cf7c2a3b2c60e6121625eaa5ca2d/Projects/STM32U5G9J-DK2/Applications/USBX/Ux_Host_HID/README.md?plain=1#L116-L122

@nickterry, the host examples provided for some boards can be tailored to run on other boards as indicated in the `README.md` files too.

https://github.com/STMicroelectronics/STM32CubeU5/blob/c8fcb26ff629cf7c2a3b2c60e6121625eaa5ca2d/Projects/STM32U5x9J-DK/Applications/USBX/Ux_Host_CDC_ACM/README.md?plain=1#L91-L92

I hope this shades more light on your questions. Please allow me to close this thread. Thank you for your comprehension.

With regards,
