### ISSUE TITLE
stm32u5a9xx.h USB_OTG mess

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/STM32CubeU5#31]
1. File [stm32u5a9xx.h](https://github.com/STMicroelectronics/STM32CubeU5/blob/main/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5a9xx.h), line 27339:
`#define USB_OTG_GCCFG_FSVMINUS_Msk 0x1U << USB_OTG_GCCFG_FSVMINUS_Pos) /*!< 0x00000004 */`
has missing opening parenthesis!
2. GINTSTS.RSTDET register field definition (`USB_OTG_GINTSTS_RSTDET`) is missing.
See: [RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf), 73.14.6 OTG core interrupt register [alternate] (OTG_GINTSTS)
3. Many USB_OTG register field names differ from those described in [RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf). Some of them are completely different. Examples:
GINTSTS.WKUPINT -> USB_OTG_GINTSTS_WKUINT
GINTSTS.IPXFR -> USB_OTG_GINTSTS_PXFR_INCOMPISOOUT
GINTSTS.GONAKEFF -> USB_OTG_GINTSTS_BOUTNAKEFF
GCCFG.FORCEHOSTPD -> USB_OTG_GCCFG_PULLDOWNEN
GCCFG.VBVALOVEN -> USB_OTG_GCCFG_VBVALEXTOEN
GCCFG.HVDMSRCEN -> USB_OTG_GCCFG_H_VDMSRCEN
GCCFG.HCDPDETEN -> USB_OTG_GCCFG_H_CDPDETEN
GCCFG.HCDPEN -> USB_OTG_GCCFG_H_CDPEN

4. It is difficult to understand why only one particular register - `OTG_HPRT` ([RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf), 73.14.30) is defined as `USBx_HPRT0` in [stm32u5xx_ll_usb.h](https://github.com/STMicroelectronics/STM32CubeU5/blob/7942fc4ea05026e4e9ce72d680f704e9433bce42/Drivers/STM32U5xx_HAL_Driver/Inc/stm32u5xx_ll_usb.h#L517C89-L517C89) header, rather than in [stm32u5a9xx.h](https://github.com/STMicroelectronics/STM32CubeU5/blob/main/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5a9xx.h) where it belongs to. `USB_OTG_HostTypeDef` might be a better place to define it. The same time, this register's fields are defined in [stm32u5a9xx.h](https://github.com/STMicroelectronics/STM32CubeU5/blob/main/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5a9xx.h) and correctly named `USB_OTG_HPRT_PSPD` etc.
Not to mention that `USBx_HPRT0` definition depends on `USBx_BASE` defined later like [this](https://github.com/STMicroelectronics/STM32CubeU5/blob/7942fc4ea05026e4e9ce72d680f704e9433bce42/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_ll_usb.c#L1253). I think it is overengineered and overcomplicated. **OTG host supports only one port.** If one really feels like more then one USB port needs to be handled in the future, why not to simply define USB1_HPRT0? - just like e.g. `UCPD1` is defined. This is just inconsistent with how other IPs' registers are defined.

It is difficult to avoid impression that this STM32U5 HAL release was prepared in rush and never updated after the first [RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf) release version had been finalized.

**Comment by RJMSTM** [comment]
Hello @tdjastrzebski,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With Regards,

**Comment by tdjastrzebski** [comment]
Hello @RJMSTM. I just discovered that more USB_OTG register definitions are missing.

- GOTGCTL.CURMOD
- GOTGCTL.OTGVER
- GOTGCTL.ASVLD
- GOTGCTL.DBCT
- GOTGCTL.CIDSTS
- GOTGCTL.EHEN
- and  GOTGCTL.BSVLD is incorrectly named USB_OTG_GOTGCTL_BSESVLD

See [RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf),  73.14.1 OTG control and status register (OTG_GOTGCTL)

**Comment by ALABSTM** [comment]
ST Internal Reference: 170735

**Comment by ALABSTM** [comment]
Hi @tdjastrzebski,

Please excuse this delayed reply. Thank you very much for this detailed report. It has been forwarded to our development teams. I will keep you informed.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 170738

**Comment by ALABSTM** [comment]
ST Internal Reference: 170739

**Comment by ALABSTM** [comment]
ST Internal Reference: 171759

**Comment by TOUNSTM** [comment]
Hello @tdjastrzebski,

> 1. File [stm32u5a9xx.h](https://github.com/STMicroelectronics/STM32CubeU5/blob/main/Drivers/CMSIS/Device/ST/STM32U5xx/Include/stm32u5a9xx.h), line 27339:
>    `#define USB_OTG_GCCFG_FSVMINUS_Msk 0x1U << USB_OTG_GCCFG_FSVMINUS_Pos) /*!< 0x00000004 */`
>    has missing opening parenthesis!

The issue you have raised has been fixed in commit 332197d7ed2d96a9ee3aaf824181c5a3bb3541cb.

With Regards,

**Comment by ALABSTM** [comment]
Hi @tdjastrzebski,

We're almost there to close this issue:
* Point 1 has already been fixed in commit 2e053bcab594083bc519a69fbc72bb95d57881db.
* Points 2 and 3 will be fixed in the frame of release **1.7.0**, coming in a couple of weeks hopefully.
* Point 4, however, has been declined by our development teams.

I will keep you informed once release **1.7.0** becomes available on GitHub.

With regards,

**Comment by tdjastrzebski** [comment]
Hi @ALABSTM, thank you for the update. nice It is good to see that ST software catches up with hardware. Batter late than never. Seriously.

**Comment by TOUNSTM** [comment]
Hello @tdjastrzebski,

The points 2 and 3 have already been fixed in the frame of [release 1.7.0 ](https://github.com/STMicroelectronics/STM32CubeU5/commit/7392378474639cdcd87a71918f5272f847454055).

Thank you for your valuable contribution. We are looking forward to reading from you again.
With Regards,
