### ISSUE TITLE
Drivers/Src: ll_utils.c: Wrong LATENCY_FREQ definition

### ISSUE THREAD

**Issue by erwango** [STMicroelectronics/STM32CubeU5#4]
It seems that some `UTILS_SCALEY_LATENCYX_FREQ` definitions are wrong:

https://github.com/STMicroelectronics/STM32CubeU5/blob/0eedae3d2a7997a2b5fbfdb57f54c7201e0827c8/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_ll_utils.c#L69-L71

`12.5000000` and `37.5000000` look erroneous.
Can you confirm ?

**Comment by ASELSTM** [comment]
ST Internal Reference: 116963

**Comment by ASELSTM** [comment]
Hi @erwango,

This issue has been fixed in the frame of version v1.1.0 of the STM32CubeU5 published recently. Please allow me then to close this thread.

With regards,
