### ISSUE TITLE
SBSFU

### ISSUE THREAD

**Issue by aitor4321** [STMicroelectronics/STM32CubeU5#45]
Hello,

I have a small question about how the SBSFU example works. Does it work in the secure zone or in the non secure zone? If it works in the non secure zone, how can I make it work in the secure zone?

Thanks in advance

**Comment by tdjastrzebski** [comment]
@aitor4321 It works in both zones. Recently I was puzzled as well so I visualized it in Excel. See below, green is Trust Zone.

![image](https://github.com/STMicroelectronics/STM32CubeU5/assets/7325277/5b8476ff-7c58-48e9-83a4-f5bd347ce5ba)

**Comment by aitor4321** [comment]
Hello @tdjastrzebski,

Thank you for responding. So, if I modify the main file of SBSFU_APPLI_SECURE and make an application that saves data in memory, will it save it in the secure zone? If someone tries to retrieve that data, could they access that memory?

**Comment by ALABSTM** [comment]
ST Internal Reference: 179481

**Comment by ALABSTM** [comment]
Hi,

@tdjastrzebski, thank you for your contribution.

@aitor4321, did the indications provided by @tdjastrzebski help you with what you are trying to do? In the meanwhile, your question has been forwarded to our development teams. I will keep you informed.

With regards,

With regards,

**Comment by aitor4321** [comment]
Hi @ALABSTM,

Yes, the instructions provided by @tdjastrzebski have helped me with what I'm trying to accomplish. Thank you!

 Looking forward to hearing from the development teams.
 
 With regards,

**Comment by ALABSTM** [comment]
Hi @aitor4321,

Back to you with an extra information from our development teams. You asked:
> If someone tries to retrieve that data, could they access that memory?

The answer is that it depends on the location where the modified `SBSFU_Appli_Secure` application saves data... If it save it to a non-secure or to a secure area in the flash memory. Hence, you have to ensure that your data is saved to a **secure** area in the flash memory.

I hope this helps. Please allow me to close this thread.

With regards,
