### ISSUE TITLE
SBSFU production mode

### ISSUE THREAD

**Issue by aitor4321** [STMicroelectronics/STM32CubeU5#47]
Hi,

Reading through the steps of how to implement the SBSFU application, it mentions that development mode is used by default. In this example, can production mode work, or does it only function with development mode? And if production mode can be used, what steps would need to be followed?

**Comment by ALABSTM** [comment]
ST Internal Reference: 180039

**Comment by ALABSTM** [comment]
Hi @aitor4321,

Your question has been forwarded to our development teams. Waiting for their feedback.

With regards,
