### ISSUE TITLE
Using SBSFU application on another device

### ISSUE THREAD

**Issue by aitor4321** [STMicroelectronics/STM32CubeU5#51]
Hi,

I want to use the SBSFU application on the STM32U575ZIT6 microcontroller instead of the B-U585I-IOT20A board. Is this possible? If it can be done, what steps should I follow?

**Comment by ALABSTM** [comment]
Hi @aitor4321,

Thank you for your question. As indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeU5/blob/main/CONTRIBUTING.md#3-support-requests-and-questions) guide, support with such topics could be found in the [ST Community](https://community.st.com/s/topiccatalog).

Please allow me to close this issue. Thank you for your comprehension.

With regards,
